# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-01-26 12:14:13
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("GeoStats")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("3D")

    BME_Mean_2_ = "BME Mean"
    geoBoundaries_IND_ADM2_2_ = "geoBoundaries-IND-ADM2"
    India_Pop_2025_1km_R2025A_UA_v1_tif = arcpy.Raster("India_Pop_2025_1km_R2025A_UA_v1.tif")
    geoBoundaries_IND_ADM2 = "geoBoundaries-IND-ADM2"

    # Process: GA Layer To Rasters (GA Layer To Rasters) (ga)
    concras = "C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb\\concras"
    Additional_rasters = arcpy.ga.GALayerToRasters(in_geostat_layer=BME_Mean_2_, out_raster=concras)[0]
    concras = arcpy.Raster(concras)

    # Process: Zonal Statistics as Table (Zonal Statistics as Table) (ia)
    ZonalSt_PopTbl = "C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb\\ZonalSt_PopTbl"
    Output_Join_Layer = ""
    arcpy.ia.ZonalStatisticsAsTable(geoBoundaries_IND_ADM2_2_, "shapeName", India_Pop_2025_1km_R2025A_UA_v1_tif, ZonalSt_PopTbl, "DATA", "SUM", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360, Output_Join_Layer)
    .save(Zonal_Statistics_as_Table)


    # Process: Raster Calculator (Raster Calculator) (ia)
    concpop_ras = "C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb\\RasterC_1"
    Raster_Calculator = concpop_ras
    concpop_ras =   concras * India_Pop_2025_1km_R2025A_UA_v1_tif
    concpop_ras.save(Raster_Calculator)


    # Process: Zonal Statistics as Table (2) (Zonal Statistics as Table) (sa)
    ZonalSt_ConcPopSumTbl = "C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb\\ZonalSt_ConcPopSumTbl"
    Output_Join_Layer_2_ = ""
    arcpy.sa.ZonalStatisticsAsTable(geoBoundaries_IND_ADM2, "shapeName", concpop_ras, ZonalSt_ConcPopSumTbl, "DATA", "SUM", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360, Output_Join_Layer_2_)
    .save(Zonal_Statistics_as_Table_2_)


    # Process: Join Field (Join Field) (management)
    ZonalSt_PopTbl_2_ = arcpy.management.JoinField(in_data=ZonalSt_PopTbl, in_field="shapeName", join_table=ZonalSt_ConcPopSumTbl, join_field="shapeName")[0]

    # Process: Add Field (Add Field) (management)
    ZonalSt_PopTbl_3_ = arcpy.management.AddField(in_table=ZonalSt_PopTbl_2_, field_name="PWM", field_type="DOUBLE")[0]

    # Process: Calculate Field (Calculate Field) (management)
    ZonalSt_PopTbl_4_ = arcpy.management.CalculateField(in_table=ZonalSt_PopTbl_3_, field="PWM", expression="!SUM!/!SUM!")[0]

    # Process: Join Field (2) (Join Field) (management)
    geoBoundaries_IND_ADM2_3_ = arcpy.management.JoinField(in_data=geoBoundaries_IND_ADM2_2_, in_field="shapeName", join_table=ZonalSt_PopTbl_4_, join_field="shapeName")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="India_Pop_2025_1km_R2025A_UA_v1.tif", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", maintainAttachments=True, maintainSpatialIndex=False, 
                          matchMultidimensionalVariable=True, nodata="NONE", outputCoordinateSystem="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", 
                          outputMFlag="Same As Input", outputZFlag="Same As Input", preserveGlobalIds=False, 
                          pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", qualifiedFieldNames=True, randomGenerator="0 ACM599", 
                          rasterStatistics="STATISTICS 1 1", resamplingMethod="NEAREST", scratchWorkspace="C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb", 
                          terrainMemoryUsage=False, tileSize="128 128", tinSaveVersion="CURRENT", 
                          transferDomains=False, transferGDBAttributeProperties=False, unionDimension=False, 
                          workspace="C:\\Users\\agwilbo\\Documents\\ArcGIS\\Projects\\India_Pb_WI\\India_Pb_WI.gdb"):
        Model()
